# Generated by Django 5.2.1 on 2025-05-20 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_territory_unit_territory_retreating_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='retreating_unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit'),
        ),
    ]
