# Generated by Django 5.2.1 on 2025-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_territory_retreating_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
