# Generated by Django 5.2.1 on 2025-05-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_unit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet')]),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('T', 'Turkey'), ('R', 'Russia')], max_length=1)),
                ('origin_territory', models.CharField(max_length=20)),
                ('target_territory', models.CharField(max_length=20)),
                ('supported_territory', models.CharField(default=None, max_length=20, null=True)),
                ('convoyed_territory', models.CharField(default=None, max_length=20, null=True)),
                ('move_type', models.CharField(choices=[('M', 'Move'), ('S', 'Support'), ('H', 'Hold'), ('C', 'Convoy'), ('R', 'Retreat')], max_length=1)),
                ('turn', models.PositiveSmallIntegerField()),
                ('submitted', models.BooleanField(default=False)),
                ('convoyed_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_convoyed_unit', to='api.unit')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('supported_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supported_unit', to='api.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_unit', to='api.unit')),
            ],
        ),
    ]
