# Generated by Django 5.2.1 on 2025-05-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_unit_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_territory',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
