# Generated by Django 5.2.1 on 2025-05-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_target_territory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supported_territory',
            new_name='other_territory',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='turn',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='order',
            name='convoyed_territory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='convoyed_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supported_unit',
        ),
        migrations.AddField(
            model_name='order',
            name='other_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_other_unit', to='api.unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='season',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('winter', 'Winter')], default='spring'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='move_type',
            field=models.CharField(choices=[('M', 'Move'), ('S', 'Support'), ('H', 'Hold'), ('C', 'Convoy'), ('R', 'Retreat'), ('B', 'Build'), ('D', 'Disband')], max_length=1),
        ),
    ]
