# Generated by Django 5.2.1 on 2025-05-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_other_territory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AddField(
            model_name='order',
            name='sandbox',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sandbox'),
        ),
        migrations.AddField(
            model_name='territory',
            name='sandbox',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sandbox'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sandbox',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sandbox'),
        ),
    ]
