# Generated by Django 5.2.1 on 2025-05-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sandbox_alter_order_game_alter_territory_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='name',
            field=models.CharField(default='default!', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sandbox',
            name='season',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('winter', 'Winter')], default='spring'),
        ),
        migrations.AddField(
            model_name='sandbox',
            name='year',
            field=models.PositiveSmallIntegerField(default=1901),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
