# Generated by Django 5.2.1 on 2025-05-22 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sandbox_name_sandbox_season_sandbox_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
