# Generated by Django 5.2.1 on 2025-05-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sandbox_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='location',
            new_name='territory',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='retreating_unit',
        ),
    ]
