# Generated by Django 5.2.1 on 2025-05-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_location_unit_territory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='origin_coast',
            field=models.CharField(blank=True, choices=[('nc', 'Nc'), ('sc', 'Sc'), ('ec', 'Ec'), ('wc', 'Wc')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='target_coast',
            field=models.CharField(blank=True, choices=[('nc', 'Nc'), ('sc', 'Sc'), ('ec', 'Ec'), ('wc', 'Wc')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='territory',
            name='has_coast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='coast',
            field=models.CharField(blank=True, choices=[('nc', 'Nc'), ('sc', 'Sc'), ('ec', 'Ec'), ('wc', 'Wc')], max_length=2, null=True),
        ),
    ]
