# Generated by Django 5.2.1 on 2025-06-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_origin_coast_order_target_coast_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='other_territory',
            new_name='supported_territory',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='other_unit',
            new_name='supported_unit',
        ),
    ]
