# Generated by Django 5.2.1 on 2025-06-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_other_territory_order_supported_territory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supported_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supported_unit', to='api.unit'),
        ),
    ]
