# Generated by Django 5.2.1 on 2025-06-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_supported_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='convoyed_territory',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='convoyed_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_convoyed_unit', to='api.unit'),
        ),
    ]
