# Generated by Django 5.2.1 on 2025-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_convoyed_territory_order_convoyed_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.RemoveField(
            model_name='order',
            name='year',
        ),
        migrations.RemoveField(
            model_name='sandbox',
            name='season',
        ),
        migrations.RemoveField(
            model_name='sandbox',
            name='year',
        ),
        migrations.AddField(
            model_name='order',
            name='turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sandbox',
            name='turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
