# Generated by Django 5.2.1 on 2025-06-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_order_season_remove_order_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='move_type',
            field=models.CharField(choices=[('M', 'Move'), ('V', 'Move via Convoy'), ('S', 'Support'), ('H', 'Hold'), ('C', 'Convoy'), ('R', 'Retreat'), ('B', 'Build'), ('D', 'Disband')], max_length=1),
        ),
    ]
