# Generated by Django 5.2.1 on 2025-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_order_move_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='disbanded',
            field=models.BooleanField(default=False),
        ),
    ]
