# Generated by Django 5.2.1 on 2025-06-12 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_unit_disbanded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FailureReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=80)),
                ('sc_exists', models.BooleanField(default=False)),
                ('territory_type', models.CharField(choices=[('S', 'sea'), ('L', 'land'), ('C', 'coast')])),
                ('has_coasts', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='convoyed_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin_coast',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supported_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='target_coast',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='has_coast',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='sc_exists',
        ),
        migrations.AddField(
            model_name='order',
            name='dislodged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='result',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDS', 'Succeeds'), ('FAILS', 'Fails')], default='PENDING', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='retreat_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='retreat_result',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, verbose_name=[('R', 'Retreat'), ('D', 'Disband')]),
        ),
        migrations.AddField(
            model_name='order',
            name='winter_order',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, verbose_name=[('B', 'Build'), ('D', 'Disband')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='move_type',
            field=models.CharField(blank=True, choices=[('M', 'Move'), ('V', 'Move via Convoy'), ('S', 'Support'), ('H', 'Hold'), ('C', 'Convoy')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_unit', to='api.unit'),
        ),
        migrations.AddField(
            model_name='territory',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='fail_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.failurereason'),
        ),
        migrations.CreateModel(
            name='TerritoryCoastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_as_coast', to='api.territorytemplate')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_as_territory', to='api.territorytemplate')),
            ],
        ),
        migrations.AddField(
            model_name='territory',
            name='territory_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.territorytemplate'),
        ),
    ]
