# Generated by Django 5.2.1 on 2025-06-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_country_failurereason_territorytemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorytemplate',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
