# Generated by Django 5.2.1 on 2025-06-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_territorytemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorycoasttemplate',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.territorytemplate'),
        ),
        migrations.AlterField(
            model_name='territorytemplate',
            name='territory_type',
            field=models.CharField(choices=[('S', 'sea'), ('L', 'land')]),
        ),
        migrations.CreateModel(
            name='CoastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('full_name', models.CharField(max_length=100)),
                ('territory_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.territorytemplate')),
            ],
        ),
        migrations.AlterField(
            model_name='territorycoasttemplate',
            name='coast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coasttemplate'),
        ),
    ]
