# Generated by Django 5.2.1 on 2025-06-17 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_territorycoasttemplate_territory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='build_territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_build_territory', to='api.territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_origin_coast', to='api.coasttemplate'),
        ),
        migrations.AddField(
            model_name='order',
            name='retreat_coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_retreat_coast', to='api.coasttemplate'),
        ),
        migrations.AddField(
            model_name='order',
            name='retreat_territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_retreat_territory', to='api.territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='supported_coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supported_coast', to='api.coasttemplate'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_target_coast', to='api.coasttemplate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='convoyed_territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_convoyed_territory', to='api.territory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_origin_territory', to='api.territory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supported_territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supported_territory', to='api.territory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_target_territory', to='api.territory'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coasttemplate'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.territory'),
        ),
    ]
