# Generated by Django 5.2.1 on 2025-06-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_build_territory_order_origin_coast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='build_territory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin_coast',
        ),
        migrations.RemoveField(
            model_name='order',
            name='retreat_coast',
        ),
        migrations.RemoveField(
            model_name='order',
            name='retreat_territory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supported_coast',
        ),
        migrations.RemoveField(
            model_name='order',
            name='target_coast',
        ),
        migrations.AlterField(
            model_name='order',
            name='convoyed_territory',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_territory',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='supported_territory',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_territory',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='coast',
            field=models.CharField(blank=True, choices=[('nc', 'Nc'), ('sc', 'Sc'), ('ec', 'Ec'), ('wc', 'Wc')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='territory',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
