# Generated by Django 5.2.1 on 2025-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_order_build_territory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.CharField(choices=[('T', 'Turkey'), ('R', 'Russia')], max_length=1),
        ),
    ]
