# Generated by Django 5.2.1 on 2025-06-17 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_unit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coasttemplate',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='coasttemplate',
            name='name',
        ),
        migrations.AlterField(
            model_name='territorycoasttemplate',
            name='coast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_as_coast', to='api.territorytemplate'),
        ),
        migrations.AlterField(
            model_name='territorycoasttemplate',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_as_territory', to='api.territorytemplate'),
        ),
    ]
