# Generated by Django 5.2.1 on 2025-06-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_coasttemplate_full_name_coasttemplate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AddField(
            model_name='country',
            name='sandbox',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sandbox'),
        ),
        migrations.AddField(
            model_name='country',
            name='scs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='territorytemplate',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countrytemplate'),
        ),
    ]
