# Generated by Django 5.2.1 on 2025-06-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_countrytemplate_remove_country_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.countrytemplate'),
            preserve_default=False,
        ),
    ]
