# Generated by Django 5.2.1 on 2025-06-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_countrytemplate_scs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='owner',
            new_name='country',
        ),
    ]
