# Generated by Django 5.2.1 on 2025-06-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_owner_unit_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorytemplate',
            name='coast_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coasttemplate'),
        ),
    ]
