# Generated by Django 5.2.1 on 2025-06-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_order_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='territorytemplate',
            old_name='coast_template',
            new_name='unit_coast',
        ),
    ]
