# Generated by Django 5.2.1 on 2025-06-17 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_coast_template_territorytemplate_unit_coast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territorytemplate',
            name='unit_coast',
        ),
        migrations.RemoveField(
            model_name='territorytemplate',
            name='unit_type',
        ),
        migrations.CreateModel(
            name='InitialUnitSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('A', 'Army'), ('F', 'Fleet')], default=None, max_length=1, null=True)),
                ('country_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countrytemplate')),
                ('territory_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.territorytemplate')),
                ('unit_coast', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coasttemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='TerritoryCoastTemplate',
        ),
    ]
