# Generated by Django 5.2.1 on 2025-06-18 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_unit_coast_initialunitsetup_coast_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_target_territory', to='api.territory'),
        ),
    ]
