# Generated by Django 5.2.1 on 2025-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_order_target_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
