# Generated by Django 5.2.1 on 2025-06-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_game_current_turn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandbox',
            old_name='turn',
            new_name='current_turn',
        ),
    ]
