# Generated by Django 5.2.1 on 2025-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_turn_sandbox_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='retreat_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sandbox',
            name='retreat_required',
            field=models.BooleanField(default=False),
        ),
    ]
