# Generated by Django 5.2.1 on 2025-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_game_retreat_required_sandbox_retreat_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='current_turn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
