# Generated by Django 5.2.1 on 2025-06-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_game_current_turn_alter_sandbox_current_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
