# Generated by Django 5.2.1 on 2025-06-22 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_unitretreatoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitretreatoption',
            name='coast',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.coasttemplate'),
            preserve_default=False,
        ),
    ]
