# Generated by Django 5.2.1 on 2025-06-23 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_unitretreatoption_coast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitretreatoption',
            name='coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coasttemplate'),
        ),
    ]
