# Generated by Django 5.2.1 on 2025-06-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_unitretreatoption_coast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_cache', models.JSONField(blank=True, default=None, null=True)),
                ('disband_cache', models.JSONField(blank=True, default=None, null=True)),
                ('turn', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('sandbox', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sandbox')),
            ],
        ),
    ]
