# Generated by Django 5.2.1 on 2025-06-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='available_builds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='needed_disbands',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
