# Generated by Django 5.2.1 on 2025-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_country_available_builds_country_needed_disbands'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorytemplate',
            name='home_center',
            field=models.BooleanField(default=False),
        ),
    ]
