# Generated by Django 5.2.1 on 2025-06-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_countrytemplate_scs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='winter_order',
            new_name='adjustment_order',
        ),
    ]
