# Generated by Django 5.2.1 on 2025-06-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_order_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unit_type',
        ),
    ]
