# Generated by Django 5.2.1 on 2025-06-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_order_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adjustment_order',
            new_name='adjustment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='build_coast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_build_coast', to='api.coasttemplate'),
        ),
        migrations.AddField(
            model_name='order',
            name='build_type',
            field=models.CharField(blank=True, choices=[('A', 'Army'), ('F', 'Fleet')], default=None, max_length=1, null=True),
        ),
    ]
