# Generated by Django 5.2.1 on 2025-06-29 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_rename_adjustment_order_order_adjustment_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phase',
            new_name='AdjustmentCache',
        ),
    ]
