# Generated by Django 5.2.1 on 2025-06-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_rename_phase_adjustmentcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fail_reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.failurereason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_origin_territory', to='api.territory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_unit', to='api.unit'),
        ),
    ]
