# Generated by Django 5.2.1 on 2025-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_unitlocationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlocationsnapshot',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
