# Generated by Django 5.2.1 on 2025-07-07 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_game_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='host',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='game',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
