# Generated by Django 5.2.1 on 2025-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_rename_host_game_creator_game_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
