# Generated by Django 5.2.1 on 2025-07-07 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_chain_countrychain_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
