# Generated by Django 5.2.1 on 2025-07-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_country_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='player',
            new_name='user',
        ),
    ]
