# Generated by Django 5.2.1 on 2025-07-08 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_rename_player_country_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 15, 30, 24, 834782, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
    ]
