# Generated by Django 5.2.1 on 2025-07-08 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_chain_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
