# Generated by Django 5.2.1 on 2025-07-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_chain_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersgames',
            name='country',
        ),
    ]
