# Generated by Django 5.2.1 on 2025-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_playersgames_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_adjudication',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='next adjudication'),
        ),
    ]
