# Generated by Django 5.2.1 on 2025-07-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_game_next_adjudication'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='submitted_orders',
            field=models.BooleanField(default=False),
        ),
    ]
