# Generated by Django 5.2.1 on 2025-07-08 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_country_submitted_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_as_gm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_as_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
