# Generated by Django 5.2.1 on 2025-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_game_gm_game_public_alter_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='settings',
            field=models.JSONField(default={'press': 'default', 'public': True}),
        ),
    ]
