# Generated by Django 5.2.1 on 2025-07-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_game_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='public',
        ),
    ]
