# Generated by Django 5.2.1 on 2025-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_game_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
