# Generated by Django 5.2.1 on 2025-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='settings',
            field=models.JSONField(default={'press': 'default', 'type': 'public'}),
        ),
    ]
