# Generated by Django 5.2.1 on 2025-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_game_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='settings',
            field=models.JSONField(default={'adjudication': {'first_turn': 7, 'first_unit': 'days', 'regular_unit': 'days', 'spring_fall': 1, 'start': 12, 'time_zone': 'us_et', 'winter_retreat': 50}, 'press': 'default', 'type': 'public'}),
        ),
    ]
