# Generated by Django 5.2.1 on 2025-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_game_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='adjudicating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sandbox',
            name='adjudicating',
            field=models.BooleanField(default=False),
        ),
    ]
