# Generated by Django 5.2.1 on 2025-07-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_game_adjudicating_sandbox_adjudicating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='game',
            name='next_adjudication',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='next adjudication'),
        ),
        migrations.AlterField(
            model_name='game',
            name='settings',
            field=models.JSONField(default={'adjudication': {'fast_adjudication': False, 'first_turn': 7, 'first_unit': 'days', 'regular_unit': 'days', 'spring_fall': 1, 'start': 12, 'timezone': 'US/Eastern', 'winter_retreat': 50}, 'press': 'default', 'type': 'public'}),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
