# Generated by Django 5.2.1 on 2025-07-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_game_created_date_alter_game_next_adjudication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='settings',
            field=models.JSONField(default={'adjudication': {'fast_adjudication': False, 'first_turn': 1, 'first_unit': 'minutes', 'regular_unit': 'minutes', 'spring_fall': 1, 'start': 15, 'timezone': 'US/Eastern', 'winter_retreat': 50}, 'press': 'default', 'type': 'public'}),
        ),
    ]
