# Generated by Django 5.2.1 on 2025-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
