# Generated by Django 5.2.1 on 2025-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_game_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
