# Generated by Django 5.2.1 on 2025-07-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_game_num_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fast_adjudication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='first_turn',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public'),
        ),
        migrations.AddField(
            model_name='game',
            name='press',
            field=models.CharField(choices=[('default', 'Default'), ('always', 'Always'), ('gunboat', 'Gunboat'), ('global', 'Global')], default='default'),
        ),
        migrations.AddField(
            model_name='game',
            name='spring_fall',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='game',
            name='timezone',
            field=models.CharField(choices=[('US/Pacific', 'Us Pacific'), ('US/Eastern', 'Us Eastern'), ('US/Mountain', 'Us Mountain')], default='US/Eastern'),
        ),
        migrations.AddField(
            model_name='game',
            name='winter_retreat',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
