# Generated by Django 5.2.1 on 2025-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_game_fast_adjudication_game_first_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
