# Generated by Django 5.2.1 on 2025-07-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_game_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='start',
            new_name='start_hour',
        ),
    ]
