# Generated by Django 5.2.1 on 2025-07-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_rename_start_game_start_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='settings',
        ),
    ]
